# Generated by Django 4.1 on 2022-12-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_feed_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "feed_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.feed"
                    ),
                ),
            ],
        ),
    ]
