# Generated by Django 4.1 on 2022-12-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_reply"),
    ]

    operations = [
        migrations.RemoveField(model_name="reply", name="feed_id",),
        migrations.AddField(
            model_name="feed", name="latitude", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="feed", name="longitude", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="reply",
            name="feed",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.feed",
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
